// One-off: fetches the termcn terminal themes (Ink set) and writes hooks/termcn-themes.ts, so the mod
// never needs the network at run time. Run: node scripts/build-termcn.mjs
// Hex values are pulled out with a regex; the registry's TypeScript is never evaluated.
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const BASE = 'https://termcn.dev/r'
const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'hooks', 'termcn-themes.ts')

// The termcn color keys the picker maps from (see toTermcnTheme in hooks/theme.ts).
const KEYS = ['accent', 'background', 'error', 'focusRing', 'foreground', 'info', 'muted', 'mutedForeground', 'primary', 'secondary', 'selection', 'success', 'warning']

const slugify = name => name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
const flatten = (hex, bg) => {
  const alpha = parseInt(hex.slice(7, 9), 16) / 255
  const out = [1, 3, 5].map(i => Math.round(parseInt(bg.slice(i, i + 2), 16) * (1 - alpha) + parseInt(hex.slice(i, i + 2), 16) * alpha))
  return '#' + out.map(v => v.toString(16).padStart(2, '0')).join('')
}
const get = async url => {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`)
  return res.json()
}

const index = await get(`${BASE}/registry.json`)
const items = index.items.filter(i => /^ink\/theme-/.test(i.name) && i.name !== 'ink/theme-provider')

const themes = []
for (const item of items) {
  const json = await get(`${BASE}/${item.name}.json`)
  const content = json.files?.[0]?.content
  const block = typeof content === 'string' ? /colors:\s*\{([^}]*)\}/.exec(content)?.[1] : undefined
  if (!block) throw new Error(`${item.name}: no colors block`)
  const found = {}
  for (const m of block.matchAll(/(\w+):\s*["'](#[0-9a-fA-F]{6}(?:[0-9a-fA-F]{2})?)["']/g)) found[m[1]] = m[2]
  const colors = {}
  for (const key of KEYS) {
    if (!found[key]) throw new Error(`${item.name}: ${key} missing or not a hex color`)
    colors[key] = found[key]
  }
  // An 8-digit value ("#e4e4e45e") has an alpha byte: blend it over the background to get a solid color.
  for (const key of KEYS) {
    if (colors[key].length === 9) colors[key] = flatten(colors[key], colors.background)
  }
  const name = json.title ?? item.title
  themes.push({ name, slug: slugify(name), colors })
}

if (new Set(themes.map(t => t.slug)).size !== themes.length) throw new Error('duplicate slugs')
themes.sort((a, b) => a.name.localeCompare(b.name))

const body = themes.map(t => `  ${JSON.stringify(t)},`).join('\n')
writeFileSync(
  OUT,
  `// Generated by scripts/build-termcn.mjs from the termcn registry (https://termcn.dev/r/registry.json).\n` +
    `// Source: https://github.com/shadcn-labs/termcn - licence: MIT (Copyright (c) 2026 Aniket Pawar). Do not edit by hand.\n` +
    `import type { TermcnRaw } from '../types'\n\n` +
    `export const TERMCN_RAW: readonly TermcnRaw[] = [\n${body}\n]\n`,
)
console.log(`wrote ${themes.length} termcn themes to ${OUT}`)
