// One-off: reads the 88 Doki themes from the VS Code extension and writes hooks/themes.ts,
// so the mod never depends on VS Code at run time. Run: node scripts/build-themes.mjs <extensionDir>
// <extensionDir> is the installed Doki Theme extension, for example
// %USERPROFILE%\.vscode\extensions\unthrottled.doki-theme-<version>.
import { readFileSync, writeFileSync } from 'node:fs'
import { basename, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const EXT = process.argv[2]
if (!EXT) {
  console.error('Usage: node scripts/build-themes.mjs <path to the Doki Theme VS Code extension folder>')
  process.exit(1)
}
const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'hooks', 'themes.ts')

// Our short color name -> the VS Code color key it comes from.
const KEYS = {
  bg: 'editor.background',
  fg: 'editor.foreground',
  accent: 'badge.background',
  muted: 'descriptionForeground',
  subtle: 'editorLineNumber.foreground',
  selection: 'list.activeSelectionBackground',
  widget: 'editorWidget.background',
  cursor: 'terminalCursor.foreground',
  red: 'terminal.ansiRed',
  green: 'terminal.ansiGreen',
  yellow: 'terminal.ansiYellow',
  blue: 'terminal.ansiBlue',
  magenta: 'terminal.ansiMagenta',
  cyan: 'terminal.ansiCyan',
  error: 'errorForeground',
  interface: 'symbolIcon.interfaceForeground',
  purple: 'charts.purple',
  func: 'symbolIcon.functionForeground',
  constant: 'symbolIcon.constantForeground',
  cls: 'symbolIcon.classForeground',
  bool: 'symbolIcon.booleanForeground',
}

const slugify = name => name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

const pkg = JSON.parse(readFileSync(join(EXT, 'package.json'), 'utf8'))
const themes = pkg.contributes.themes.map(entry => {
  const colors = JSON.parse(readFileSync(join(EXT, entry.path), 'utf8')).colors
  const picked = {}
  for (const [short, key] of Object.entries(KEYS)) {
    const value = colors[key]
    if (typeof value !== 'string' || !/^#[0-9a-fA-F]{6}/.test(value)) {
      throw new Error(`${entry.path}: ${key} missing or not a hex color (${value})`)
    }
    picked[short] = value.slice(0, 7) // drop an 8-digit alpha suffix
  }
  // The file basename is unique ("Ram", "Mai Dark"); the label repeats the series ("Re:Zero:  Ram").
  const name = basename(entry.path, '.theme.json')
  return { name, slug: slugify(name), dark: entry.uiTheme !== 'vs', colors: picked }
})

const slugs = new Set(themes.map(t => t.slug))
if (slugs.size !== themes.length) throw new Error('duplicate slugs')
themes.sort((a, b) => Number(b.dark) - Number(a.dark) || a.name.localeCompare(b.name))

const body = themes.map(t => `  ${JSON.stringify(t)},`).join('\n')
writeFileSync(
  OUT,
  `// Generated by scripts/build-themes.mjs from ${basename(EXT)}. Do not edit by hand.\n` +
    `import type { DokiTheme } from '../types'\n\n` +
    `export const THEMES: readonly DokiTheme[] = [\n${body}\n]\n`,
)
console.log(`wrote ${themes.length} themes (${themes.filter(t => t.dark).length} dark, ${themes.filter(t => !t.dark).length} light) to ${OUT}`)
